language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
before_script:
  - npm prune
script:
  - npm run cover
  - npm run check-coverage
after_success:
  - npm run semantic-release
  - npm run report-coverage
branches:
  only:
  - master
